apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosaics-storage 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/storage/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosaics-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
