apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mosaics-service
  name: mosaics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mosaics-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mosaics-service
    spec:
      containers:
      - image: mosaics-service:latest
        name: mosaics-service
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 1
        volumeMounts:
          - mountPath: /data
            name: mosaics-storage
      volumes:
        - name: mosaics-storage
          persistentVolumeClaim:
            claimName: mosaics-storage-pvc
              
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mosaics-service
  name: mosaics-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mosaics-service
  type: ClusterIP
